### ISSUE TITLE
not working on macOS Big Sur M1

### ISSUE THREAD

**Issue by seephirot** [goplusjs/gopherjs#33]
on a fresh install on macosx (m1 hw, Big Sur) does not work.

OS: macOS Big Sur 11.2.3
HW: Apple M1 8/8 - 16Gb.
go version : go.16.2 darwin/arm64

steps to reproduce the problem :

on fresh install, install gopherjs as per instructions : go get -u github.com/goplusjs/gopherjs, than try to build something with the usual "gopherjs build main.go" (main.go or whatever) 

results :
../../../../../../src/syscall/syscall_darwin.go:225:25: undeclared name: libc_fstat64_trampoline
../../../../../../src/syscall/syscall_darwin.go:227:25: undeclared name: libc_fstatfs64_trampoline
../../../../../../src/syscall/syscall_darwin.go:231:25: undeclared name: libc_lstat64_trampoline
../../../../../../src/syscall/syscall_darwin.go:233:25: undeclared name: libc_stat64_trampoline
../../../../../../src/syscall/syscall_darwin.go:235:25: undeclared name: libc_statfs64_trampoline
../../../../../../src/syscall/syscall_darwin.go:239:25: undeclared name: libc_fstatat64_trampoline

Same result with "gopherjs server"

any suggestion how to fix or  workaround the problem ?
thanks in advance

**Comment by nevkontakte** [comment]
Are you able to reproduce the problem on an intel-based mac? Unfortunately I don't have access to a mac (intel or m1), so it is hard for me to know what's going on.

~~Also, when building with gopherjs, are you setting GOPHERJS_ROOT to a Go 1.12 installation? If not, that might be another reason for errors. Note that the current master still only supports Go 1.12 (although I'm very close to finishing 1.16 support).~~

Edit, my bad, `goplusjs/gopherjs` does support Go 1.16 already.

**Comment by seephirot** [comment]
unfortunately I don't own a intel-based Mac, I cannot try :( 

  my guess is that is something specific in macOS Big Sur instead of a hw(or kernel) difference. Dunno enough.. I can try via VMs if that could help.

**Comment by nevkontakte** [comment]
Well, the syscall package is responsible for interaction with the kernel, so it could be either differences between Big Sur and the previous version, or between darwin kernel on intel vs arm. Which one is the case I can't tell for sure, but I know that the Go team had to do a lot of work to support Go on M1, so breakages in that area are more likely.

**Comment by seephirot** [comment]
look like the culpit is the new linking system (proprietary obviously) in Big Sur,  /usr/lib/libSystem.B.dylib does not exist anymore ( was basically ld cache of macOS) and also the dynlib are not directly available, are callable only thru dlopen(). This should explain the unresolved symbols....

but I don't use syscall in gopherjs (as far i'm aware), there's a way to compile it without ?

**Comment by seephirot** [comment]
just to clarify, go itself works and build/run fine, only gopherjs return this undefined symbols.

**Comment by nevkontakte** [comment]
The error above is actually a compile-time error, not a linker error. GopherJS doesn't do linking in a traditional sense. So you need to examine your package dependency tree to find out why syscall ends up being built. In principle, GopherJS does [support syscalls](https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md) when executing on nodejs, albeit not perfectly.

The gist of the issue is that GopherJS has a set of overlays to the standard library, and in your case [this customization](https://github.com/goplusjs/gopherjs/blob/master/compiler/natives/src/syscall/syscall_darwin.go) expects some symbols to be declared that the Go standard library doesn't define. Why is that — that's a question I don't know how to answer at the moment.

There's also a larger issue at play here: https://github.com/gopherjs/gopherjs/issues/693. In a perfect world GopherJS wouldn't compile os-specific code, but changing that is not easy and it'll be some time before we find a solution for that…

**Comment by visualfc** [comment]
> on a fresh install on macosx (m1 hw, Big Sur) does not work.
> 
> OS: macOS Big Sur 11.2.3
> HW: Apple M1 8/8 - 16Gb.
> go version : go.16.2 darwin/arm64
> 
> steps to reproduce the problem :
> 
> on fresh install, install gopherjs as per instructions : go get -u github.com/goplusjs/gopherjs, than try to build something with the usual "gopherjs build main.go" (main.go or whatever)
> 
> results :
> ../../../../../../src/syscall/syscall_darwin.go:225:25: undeclared name: libc_fstat64_trampoline
> ../../../../../../src/syscall/syscall_darwin.go:227:25: undeclared name: libc_fstatfs64_trampoline
> ../../../../../../src/syscall/syscall_darwin.go:231:25: undeclared name: libc_lstat64_trampoline
> ../../../../../../src/syscall/syscall_darwin.go:233:25: undeclared name: libc_stat64_trampoline
> ../../../../../../src/syscall/syscall_darwin.go:235:25: undeclared name: libc_statfs64_trampoline
> ../../../../../../src/syscall/syscall_darwin.go:239:25: undeclared name: libc_fstatat64_trampoline
> 
> Same result with "gopherjs server"
> 
> any suggestion how to fix or workaround the problem ?
> thanks in advance

I don't have M1 MacOS,  you can try run  
```
$ GOOS=darwin GOARCH=amd64 gopherjs build -a -v main.go
```

---------
 i'm create darwin_amd64 branch, please check and test on macos M1

`https://github.com/goplusjs/gopherjs/tree/arm64`

**Comment by seephirot** [comment]
With the last stable,  I receive this output :

/Users/alex/go/src/internal/unsafeheader
/Users/alex/go/src/internal/cpu
/Users/alex/go/src/internal/bytealg
/Users/alex/go/src/runtime/internal/sys
/Users/alex/go/src/github.com/gopherjs/gopherjs/js
/Users/alex/go/src/runtime
/Users/alex/go/src/internal/reflectlite
/Users/alex/go/src/errors
/Users/alex/go/src/math/bits
/Users/alex/go/src/math
/Users/alex/go/src/unicode/utf8
/Users/alex/go/src/strconv
/Users/alex/go/src/internal/race
/Users/alex/go/src/sync/atomic
/Users/alex/go/src/runtime/internal/atomic
/Users/alex/go/src/sync
/Users/alex/go/src/io
/Users/alex/go/src/unicode
/Users/alex/go/src/strings
/Users/alex/go/src/reflect
/Users/alex/go/src/syscall/js
/Users/alex/go/src/internal/oserror
../../../../../../src/syscall/syscall_darwin.go:225:25: undeclared name: libc_fstat64_trampoline
../../../../../../src/syscall/syscall_darwin.go:227:25: undeclared name: libc_fstatfs64_trampoline
../../../../../../src/syscall/syscall_darwin.go:231:25: undeclared name: libc_lstat64_trampoline
../../../../../../src/syscall/syscall_darwin.go:233:25: undeclared name: libc_stat64_trampoline
../../../../../../src/syscall/syscall_darwin.go:235:25: undeclared name: libc_statfs64_trampoline
../../../../../../src/syscall/syscall_darwin.go:239:25: undeclared name: libc_fstatat64_trampoline

Using the arm64 branch, works !

On side note, I’ve checkout this branch in my src (so, get named src/gopherjs)
Using import “syscall/js” , js.Object wasn’t found 
( Error: Object not declared by package js )
Using import “gopherjs/js”  everything work’d just fine.

Pretty sure that's unrelated with my previous issue, but I thoght was worthing mention it.

Thanks again, your little patch fixed everything :)

**Comment by visualfc** [comment]
@seephirot I'm merge master to https://github.com/goplusjs/gopherjs/tree/arm64 , please try can work on macOS M1

**Comment by seephirot** [comment]
nope, not working with the current master.
I saw from the commit that you added and then reverted.... did you found a better way or regression problems ?

**Comment by visualfc** [comment]
> nope, not working with the current master.
> I saw from the commit that you added and then reverted.... did you found a better way or regression problems ?

check arm64 branch last commit can work?

**Comment by seephirot** [comment]
- arm64 branch works with no issues.
- current master return again : 

../../../../../../src/syscall/syscall_darwin.go:225:25: undeclared name: libc_fstat64_trampoline
../../../../../../src/syscall/syscall_darwin.go:227:25: undeclared name: libc_fstatfs64_trampoline
../../../../../../src/syscall/syscall_darwin.go:231:25: undeclared name: libc_lstat64_trampoline
../../../../../../src/syscall/syscall_darwin.go:233:25: undeclared name: libc_stat64_trampoline
../../../../../../src/syscall/syscall_darwin.go:235:25: undeclared name: libc_statfs64_trampoline
../../../../../../src/syscall/syscall_darwin.go:239:25: undeclared name: libc_fstatat64_trampoline

what do you want me to test ?

**Comment by visualfc** [comment]
> * arm64 branch works with no issues.
> * current master return again :
> 
> ../../../../../../src/syscall/syscall_darwin.go:225:25: undeclared name: libc_fstat64_trampoline
> ../../../../../../src/syscall/syscall_darwin.go:227:25: undeclared name: libc_fstatfs64_trampoline
> ../../../../../../src/syscall/syscall_darwin.go:231:25: undeclared name: libc_lstat64_trampoline
> ../../../../../../src/syscall/syscall_darwin.go:233:25: undeclared name: libc_stat64_trampoline
> ../../../../../../src/syscall/syscall_darwin.go:235:25: undeclared name: libc_statfs64_trampoline
> ../../../../../../src/syscall/syscall_darwin.go:239:25: undeclared name: libc_fstatat64_trampoline
> 
> what do you want me to test ?

thanks, I'm now update arm64 branch,  please update and check `gopherjs run` can work on arm64.

**Comment by seephirot** [comment]
the arm64 branch works correctly as far I can say. I use mainly "build" and "serve" so I wrote a lil test and tried also "run", no error messages, expected output ... all working as should.

**Comment by visualfc** [comment]
> the arm64 branch works correctly as far I can say. I use mainly "build" and "serve" so I wrote a lil test and tried also "run", no error messages, expected output ... all working as should.

thanks, merge arm64 to master.
